name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: PEP 8 check
        run: |
          pip install flake8
          # stop the build if the code isn't PEP 8 compliant
          # the GitHub editor is 127 chars wide so I'd consider it a reasonable line length limit
          flake8 . --max-line-length 127 --per-file-ignores="__init__.py:F401, E402 test/*: E402"
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test/command_tests.py
